# Generated by Django 4.1.3 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('min_salary', models.CharField(max_length=20)),
                ('max_salary', models.CharField(max_length=20)),
                ('avg_salary', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'scrap',
            },
        ),
    ]
